;;; ig-packages-load.el --- Package.el config  -*- lexical-binding: t; -*-

;;; Commentary:
;; Package.el config

;;; Code:

(require 'package)
(push '("melpa" . "https://melpa.org/packages/") package-archives)
(setq package-user-dir (expand-file-name "packages/install" ig-cache-dir)
      package-native-compile t
      package-quickstart t
      package-quickstart-file (expand-file-name "packages/package-quickstart.el" ig-cache-dir)
      package-gnupghome-dir (expand-file-name "packages/gnupg" ig-cache-dir))
;; Holds package-selected-packages that is autogenerated
(load (expand-file-name "packages/selected-packages" ig-cache-dir) t t nil)
(package-activate-all)

;; Local Variables:
;; byte-compile-warnings: (not free-vars)
;; End:
(provide 'ig-packages-load)
;;; ig-packages-load.el ends here
