#!/usr/bin/env bash

if [ $# != 2 ] ; then
    echo 'Expected exactly two arguments'
    exit 1
fi

if [ -f "$1" -a -f "$2" ]; then
    xterm -e vimdiff "$1" "$2" &
elif [ -d "$1" -a -d "$2" ]; then
    if diff -r "$1" "$2" > /dev/null 2>&1; then
        echo 'Equal'
    else
        echo 'Not equal'
    fi
else
    if [ -f "$1" ]; then
        type_of_1='file'
    else
        type_of_1='directory'
    fi
    if [ -f "$2" ]; then
        type_of_2='file'
    else
        type_of_2='directory'
    fi
    echo "Arguments are of different type ($type_of_1/$type_of_2)"
    exit 1
fi

