[General]
  snippetfile = "~/.config/pet/snippets.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf --no-preview"
  backend = "gist"
  sortby = "description"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  public = false
  auto_sync = false

[GitLab]
  file_name = "pet-snippet.toml"
  access_token = ""
  url = ""
  id = ""
  visibility = "private"
  auto_sync = false
