;;; early-init.el --- Early init code -*- lexical-binding: t; -*-

;;; Commentary:
;; Early init config

;;; Code:

(let ((additional-lisp-dir (expand-file-name "lisp" user-emacs-directory)))
  (push additional-lisp-dir load-path))
(require 'ig-common)
(push (expand-file-name "eln-cache" ig-cache-dir) native-comp-eln-load-path)
(defvar ig--file-name-handler-alist file-name-handler-alist)
(setq default-frame-alist '((font . "DejaVuSansMono Nerd Font Mono-14") (tool-bar-lines . 0))
      gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6
      file-name-handler-alist nil
      frame-resize-pixelwise t
      frame-inhibit-implied-resize t
      generated-autoload-file (expand-file-name "local-autoloads/loaddefs.el" ig-cache-dir))
(setq-default inhibit-redisplay t
              inhibit-message t
	      load-prefer-newer t)
(add-hook 'window-setup-hook
          (lambda ()
            (setq-default inhibit-redisplay nil
                          inhibit-message nil)
            (redisplay)))
(add-hook 'emacs-startup-hook
	  (lambda ()
	    (setq gc-cons-threshold 16777216; 16 Mb
		  gc-cons-percentage 0.1
		  file-name-handler-alist ig--file-name-handler-alist)
	    (makunbound 'ig--file-name-handler-alist)))

(require 'package)
(push '("melpa" . "https://melpa.org/packages/") package-archives)
(setq package-enable-at-startup t
      package-user-dir (expand-file-name "packages/install" ig-cache-dir)
      package-native-compile t
      package-quickstart t
      package-quickstart-file (expand-file-name "packages/package-quickstart.el" ig-cache-dir)
      package-gnupghome-dir (expand-file-name "packages/gnupg" ig-cache-dir))
;; Holds package-selected-packages that is autogenerated
(load (expand-file-name "packages/selected-packages" ig-cache-dir) t t nil)

;; Local Variables:
;; byte-compile-warnings: (not free-vars)
;; End:
(provide 'early-init)
;;; early-init.el ends here

